# DATABASE

spring.datasource.url=jdbc:sqlserver://save-your-links.database.windows.net:1433;database=free-sql-db-2185846;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=CloudSAdf8386fb@save-your-links
spring.datasource.password=Sonia12021996@
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# MICROSOFT ENTRE ID
#spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cb19419f-059e-40c8-afd2-c6cd3a87ac2d.ciamlogin.com/cb19419f-059e-40c8-afd2-c6cd3a87ac2d/v2.0
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://cb19419f-059e-40c8-afd2-c6cd3a87ac2d.ciamlogin.com/cb19419f-059e-40c8-afd2-c6cd3a87ac2d/discovery/v2.0/keys