spring.application.name=save-your-links-api
server.servlet.context-path=/save-your-links-api


# DATABASE

#spring.datasource.url=jdbc:sqlserver://save-your-links.database.windows.net:1433;database=free-sql-db-2185846;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#spring.datasource.username=CloudSAdf8386fb@save-your-links
#spring.datasource.password=Sonia12021996@
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect